import React,{useEffect,useMemo,useState} from 'react';
import WebRTCPlayer from './components/WebRTCPlayer';
import WebGLHUD from './components/WebGLHUD';
import GeofenceEditor from './components/GeofenceEditor';
import AnalyticsDashboard from './components/AnalyticsDashboard';
import CommandPalette from './components/CommandPalette';
import DigitalTwin from './components/DigitalTwin';
import IncidentTimeline from './components/IncidentTimeline';
import TargetGraph from './components/TargetGraph';
import useTelemetry from './hooks/useTelemetry';
import './style.css';
const STREAMS=[
{id:'CAM-01',name:'NORTH GATE',zone:'PERIMETER',color:'cyan'},
{id:'CAM-02',name:'LOADING BAY',zone:'INDUSTRIAL',color:'lime'},
{id:'CAM-03',name:'WEST CORRIDOR',zone:'INTERNAL',color:'violet'},
{id:'CAM-04',name:'PARKING DECK',zone:'EXTERNAL',color:'amber'}];
const targets={
'CAM-01':[{bbox:{x1:.18,y1:.22,x2:.31,y2:.55},label:'PERSON',confidence:.96}],
'CAM-02':[{bbox:{x1:.48,y1:.20,x2:.60,y2:.57},label:'PERSON',confidence:.94}],
'CAM-03':[{bbox:{x1:.30,y1:.30,x2:.40,y2:.65},label:'PERSON',confidence:.89}],
'CAM-04':[{bbox:{x1:.12,y1:.40,x2:.27,y2:.70},label:'VEHICLE',confidence:.93}]};
function CameraCard({s,active,onSelect,missionMode}){const {telemetry}=useTelemetry(s.id);const [fenceMode,setFenceMode]=useState(false);const [fence,setFence]=useState([]);const whep=(import.meta.env.VITE_WHEP_URL||'').replace('{stream_id}',s.id);return <article className={`camera-card ${active?'active':''} tone-${s.color}`} onClick={onSelect}><div className="cam-head"><span><i className="dot"/> {s.id}</span><b>{s.name}</b><em>{s.zone}</em></div><div className="video-wrap"><WebRTCPlayer streamId={s.id} whepUrl={whep||undefined}/><WebGLHUD targets={targets[s.id]} geofence={fence}/><div className="ai-chip">AI VISION <b>98.2%</b></div><div className="target-tags">{targets[s.id].map((x,i)=><span key={i}>{x.label} {Math.round(x.confidence*100)}%</span>)}</div><GeofenceEditor streamId={s.id} enabled={fenceMode} onSaved={setFence}/><div className="corner tl"/><div className="corner br"/>{missionMode&&<div className="mission-crosshair">+</div>}</div><div className="cam-foot"><span>{telemetry.fps.toFixed(1)} FPS</span><span>{telemetry.tracks} TRACKS</span><span>{telemetry.inference_ms.toFixed(1)}ms</span><button onClick={e=>{e.stopPropagation();setFenceMode(v=>!v)}}>{fenceMode?'EXIT ROI':'DRAW ROI'}</button></div></article>}
export default function App(){const [active,setActive]=useState('CAM-01');const [view,setView]=useState('matrix');const [palette,setPalette]=useState(false);const [mission,setMission]=useState(false);const [twin,setTwin]=useState(false);const [search,setSearch]=useState('');const [alerts,setAlerts]=useState([{id:1,type:'RE-ID',text:'Target T-204 matched CAM-02 → CAM-03',time:'12:41:08',level:'info'},{id:2,type:'VLM',text:'Anomaly review queued on NORTH GATE',time:'12:40:51',level:'warn'}]);const activeStream=useMemo(()=>STREAMS.find(s=>s.id===active)||STREAMS[0],[active]);const {telemetry}=useTelemetry(active);const filtered=STREAMS.filter(s=>(s.id+' '+s.name+' '+s.zone).toLowerCase().includes(search.toLowerCase()));
useEffect(()=>{const f=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(true)}if(e.key==='Escape')setMission(false)};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
const action=id=>{if(id==='focus')setView('focus');if(id==='twin'){setTwin(true);setView('matrix')}if(id==='mission')setMission(true);if(id==='clear')setAlerts([]);if(id==='replay')alert('Synchronized replay armed for incident #42');};
return <main className={`app ${mission?'mission-mode':''}`}><header className="topbar"><div className="brand"><span className="brand-mark">V</span><div><small>VANTA // VISION INTELLIGENCE</small><h1>COMMAND CENTER <span>v3.3 ULTRA</span></h1></div></div><div className="top-actions"><div className="health"><i/> ALL SYSTEMS NOMINAL</div><button onClick={()=>setMission(v=>!v)}>{mission?'EXIT MISSION':'⌁ MISSION'}</button><button onClick={()=>setPalette(true)}>⌘K</button></div></header><nav className="commandbar"><div className="breadcrumbs">MISSION / <b>LIVE MATRIX</b> / {activeStream.id}</div><div className="nav-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search camera / zone / target…"/></div><div className="view-tabs"><button className={view==='matrix'?'on':''} onClick={()=>setView('matrix')}>MATRIX</button><button className={view==='focus'?'on':''} onClick={()=>setView('focus')}>FOCUS</button><button className={twin?'on':''} onClick={()=>setTwin(v=>!v)}>TWIN</button></div></nav>{twin&&<DigitalTwin streams={STREAMS} active={active} onSelect={id=>{setActive(id);setTwin(false)}}/>}<section className={`workspace ${view==='focus'?'focus-mode':''}`}><div className="matrix">{filtered.map(s=><CameraCard key={s.id} s={s} active={active===s.id} onSelect={()=>setActive(s.id)} missionMode={mission}/>)}</div><aside className="right-rail"><AnalyticsDashboard telemetry={telemetry} streamCount={STREAMS.length} alerts={alerts}/><IncidentTimeline onReplay={()=>action('replay')}/><TargetGraph/><section className="alert-panel"><div className="section-title">LIVE INTELLIGENCE <span>STREAM</span></div>{alerts.map(a=><div className={`alert ${a.level}`} key={a.id}><b>{a.type}</b><p>{a.text}</p><time>{a.time}</time></div>)}<button className="rail-btn" onClick={()=>setAlerts([])}>CLEAR EVENT BUFFER</button></section></aside></section><footer><span>WEBRTC <b>WHEP</b></span><span>WEBGL <b>60 FPS</b></span><span>RE-ID <b>ONLINE</b></span><span>VLM <b>READY</b></span><span>EDGE <b>SYNC</b></span><span className="footer-right">LATENCY TARGET <b>&lt;50ms</b></span></footer><CommandPalette open={palette} onClose={()=>setPalette(false)} onAction={action}/></main>}
